# 代谢物鉴定{#chapID}

代谢组学最重要的目标之一，就是获取样品中有哪些代谢物，并知道该代谢物的含量信息。因而代谢物的鉴定，成为在峰检测之后最为重要的工作，只有在获取准确的代谢物鉴定结果的基础上，才可以准确的做接下来的生物信息学的各项分析。

## 代谢物鉴定方法介绍
通过与标准谱图库里的MS2谱图进行比对，从而获取采集到的代谢物的信息是最常用且有效的方法，对于少量的数据，可以用在线的代谢物鉴定工具进行处理即可，如METLIN，MassBank，MoNA等。另外也可以通过理论谱图进行鉴定，如CFM-ID，MetFrag等。

对于植物代谢物，[GNPS](https://gnps.ucsd.edu/ProteoSAFe/static/gnps-splash.jsp)谱图库（[GNPS Public Spectral Libraries](https://gnps.ucsd.edu/ProteoSAFe/libraries.jsp)）含有大量的自然产物信息，GNPS网站支持批量通过谱图比对进行代谢物鉴定，也是非常不错的代谢物鉴定工具。除此之外，GNPS包含了很多植物代谢组学和自然产物相关的数据处理分析的工具，如有兴趣，可以自行去官方网站了解学习，在此不多赘述。

特别要注意的是，在代谢物鉴定的时候，一定要选择与自己数据采集时相对应的仪器平台的标准谱图进行比较。这是因为，在LC-MS中采集到的MS2谱图，不同的仪器平台会有很大的差异，Q-TOF和Obitrap的谱图在大多数情况下显著不同，同时，即便同一平台，不同仪器之间的谱图也会略有差异，但仍可用于代谢物鉴定，只是对鉴定的可信度略有影响。而在MassBank/MoNA谱图库中，包含了来自所有仪器平台的谱图信息，因而，在利用该谱图库进行代谢物鉴定时一定要非常注意。另外，METLIN数据库很多时候会屏蔽部分IP地址，因而国内很多地方可能无法使用，对我们会造成不便，目前美国的IP地址基本可以访问。

## 常用鉴定工具
### 利用MS-DIAL进行DDA数据处理并进行代谢物鉴定
MS-DIAL软件的[官方文档](https://mtbinfo-team.github.io/mtbinfo.github.io/MS-DIAL/tutorial)有较详细的说明，

## 自行进行代谢物鉴定
由于很多代谢物谱图库包含了大量冗余信息，包含很多与自己数据采集时仪器平台不一致的代谢物谱图，同时对鉴定结果不易批量处理，因而，自行进行代谢物鉴定也是非常不错的途径，且可以自行定制代谢物鉴定的比对方法，考虑更多的因素到代谢物鉴定当中来，通过脚本进行自动化代谢物鉴定也是非常常见的方式。

对于利用谱图比对的方式进行代谢物鉴定，首先需要有谱图相似度的比对方法，并对相似度作出正确评判，目前最常用的相似度判断方法为点积(Dot Product)，可以根据不同的目的和谱图库特性选择是正向(Forward)还是反向(Reverse)匹配进行计算。一般对于利用标准品采集获取标准谱图库，我们认为标准谱图库是精准的，可以严格作为判定标准，因而将标准谱图库做正向匹配，获得Forward Dot Product，从而进行代谢物鉴定。

